### ISSUE TITLE
Footnote changes

### ISSUE THREAD

**Issue by jjhutchi** [pbaylis/vse-risk-tool#2]
## Main tab
- [x] Remove footnote, "Workers" Number of workers..."

## Econ detail tab
- [x] Include footnote, "Workers" Number of workers..."
- [x] Include footnote, Subsector centrality: necessity of subsector to functioning of the rest of economy (0-100, least to most necessary)
- [x] Include footnote, Subsector GDP share: subsector's fraction of total GDP
- [x] Include footnote, Sector employees (avg 2019): Number of workers in sector across all occupations.

## Household tab
- [x] Include footnotes about census measures

**Comment by pbaylis** [comment]
All except HH footnotes fixed by 98def64a92d9e037ddac2d388b405ed6c3c62440

**Comment by simagae** [comment]
Lives with health worker: lives with someone who works in ambulatory health care services, hospitals, or nursing and residential care facilities

Public transit: takes public transit to work, including bus, subway/elevated rail, light rail/streetcar/commuter train and passenger ferry, but excluding carpooling

Crowded dwelling: lives in an unsuitable dwelling, where a dwelling is deemed unsuitable if it has too few bedrooms for the size and composition of the household, according to the National Occupancy Standard
**Works** from home: works from home
Low income: has low income or is part of a low-income economic family, according to the Market Basket Measure
Multi-generational household: lives in a multi-generational household
Lives with 60+: aged 60 years and over or lives with someone aged 60 and over
**Lives with kids under 6**: lives with children aged 0 to 5
Lives with kids between 6 and 12: lives with children aged 6 to 12
Age of worker: age 60 and over
Age of worker: 15-24
Age of worker: 25-34
Age of worker: 35-44
Age of worker: 45-54
Age of worker: 55-64
Age of worker: 65-74
Age of worker: 75 and over
Language: language most often spoken at home is not an official language
Immigrant: recent immigrant to Canada (less than 10 years)
Lone parent: lone parent
Poor neighbourhood: lives in a Census subdivision with high poverty rates
Mental health: reports a mental health condition

**Comment by pbaylis** [comment]
Fixed by 74dddb1a9caa8cbd542943ad2beb1818230050aa
